### ISSUE TITLE
the knocker is null

### ISSUE THREAD

**Issue by AshLore** [MProductionsmado/The-Knocker#19]
so i was playing casually with my friend and my server crashed. 
i remember seeing the knocker just out of my vision as i was sleeping then yeah..
this was the error:

[20:48:10] [Server thread/ERROR] [ne.mi.ev.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.world.entity.Entity.m_20185_()" because "knocker" is null
	Index: 2
	Listeners:
		0: NORMAL
		1: ASM: class com.cupboard.event.EventHandler onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		2: ASM: net.mcreator.theknocker.TheKnockerMod@7131b846 tick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		3: ASM: net.minecraftforge.common.ForgeInternalHandler@52ed0107 onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
		4: ASM: com.mrcrayfish.framework.event.ForgeEvents@3c9c68bf onServerTick(Lnet/minecraftforge/event/TickEvent$ServerTickEvent;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_20185_()" because "knocker" is null
	at TRANSFORMER/the_knocker@1.4.0/net.mcreator.theknocker.procedures.SpawnknockerProcedure.execute(SpawnknockerProcedure.java:68)
	at TRANSFORMER/the_knocker@1.4.0/net.mcreator.theknocker.procedures.KnockeventProcedure.execute(KnockeventProcedure.java:66)
	at TRANSFORMER/the_knocker@1.4.0/net.mcreator.theknocker.procedures.KnocksleepProcedure.lambda$execute$1(KnocksleepProcedure.java:65)
	at TRANSFORMER/the_knocker@1.4.0/net.mcreator.theknocker.TheKnockerMod.lambda$tick$2(TheKnockerMod.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/the_knocker@1.4.0/net.mcreator.theknocker.TheKnockerMod.tick(TheKnockerMod.java:84)
	at TRANSFORMER/the_knocker@1.4.0/net.mcreator.theknocker.__TheKnockerMod_tick_ServerTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.0/net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:950)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:835)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
	at java.base/java.lang.Thread.run(Thread.java:840)
[20:48:10] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_20185_()" because "knocker" is null
	at net.mcreator.theknocker.procedures.SpawnknockerProcedure.execute(SpawnknockerProcedure.java:68) ~[the_knocker-1.4.0-forge-1.20.1.jar%23172!/:?] {re:classloading}
	at net.mcreator.theknocker.procedures.KnockeventProcedure.execute(KnockeventProcedure.java:66) ~[the_knocker-1.4.0-forge-1.20.1.jar%23172!/:?] {re:classloading}
	at net.mcreator.theknocker.procedures.KnocksleepProcedure.lambda$execute$1(KnocksleepProcedure.java:65) ~[the_knocker-1.4.0-forge-1.20.1.jar%23172!/:?] {re:classloading}
	at net.mcreator.theknocker.TheKnockerMod.lambda$tick$2(TheKnockerMod.java:84) ~[the_knocker-1.4.0-forge-1.20.1.jar%23172!/:?] {re:classloading}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:mixin}
	at net.mcreator.theknocker.TheKnockerMod.tick(TheKnockerMod.java:84) ~[the_knocker-1.4.0-forge-1.20.1.jar%23172!/:?] {re:classloading}
	at net.mcreator.theknocker.__TheKnockerMod_tick_ServerTickEvent.invoke(.dynamic) ~[the_knocker-1.4.0-forge-1.20.1.jar%23172!/:?] {re:classloading,pl:eventbus:B}
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2352!/:?] {}
	at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:950) ~[forge-1.20.1-47.3.0-universal.jar%23186!/:?] {re:mixin,re:classloading,pl:mixin:APP:modernfix-forge.mixins.json:perf.potential_spawns_alloc.ForgeEventFactoryMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:835) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23181!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:core.MinecraftServerMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.dedicated_reload_executor.MinecraftServerMixin,pl:mixin:APP:majruszlibrary-common.mixins.json:MixinMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
[20:48:10] [Server thread/FATAL] [ne.mi.co.ForgeMod/]: Preparing crash report with UUID 474b0c97-bdf4-4d64-91ab-5804b0a5bde0
[20:48:10] [Server thread/ERROR] [minecraft/MinecraftServer]: This crash report has been saved to: /server/./crash-reports/crash-2024-11-05_20.48.10-server.txt

**Comment by AshLore** [comment]
forgot to add version is 1.21.1 knocker version is 1.4.0

**Comment by mpustovoi** [comment]
Same issue on 1.20.1
Waiting for a fix
