### ISSUE TITLE
' "knocker" is null ' ERROR

### ISSUE THREAD

**Issue by Domin0-06** [MProductionsmado/The-Knocker#22]
So I added "the knocker" to my modpack, but at night found this error. Hope it'll be fixed soon..

```
[21:51:51] [Server thread/ERROR]:Encountered an unexpected exceptionjava.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_20185_()" because "knocker" is null
	at net.mcreator.theknocker.procedures.SpawnknockerProcedure.execute(SpawnknockerProcedure.java:68) ~[the_knocker-1.4.0-forge-1.20.1.jar%23182!/:?]
	at net.mcreator.theknocker.procedures.KnockeventProcedure.execute(KnockeventProcedure.java:66) ~[the_knocker-1.4.0-forge-1.20.1.jar%23182!/:?]
	at net.mcreator.theknocker.procedures.KnocksleepProcedure.lambda$execute$1(KnocksleepProcedure.java:65) ~[the_knocker-1.4.0-forge-1.20.1.jar%23182!/:?]
	at net.mcreator.theknocker.TheKnockerMod.lambda$tick$2(TheKnockerMod.java:84) ~[the_knocker-1.4.0-forge-1.20.1.jar%23182!/:?]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at net.mcreator.theknocker.TheKnockerMod.tick(TheKnockerMod.java:84) ~[the_knocker-1.4.0-forge-1.20.1.jar%23182!/:?]
	at net.mcreator.theknocker.__TheKnockerMod_tick_ServerTickEvent.invoke(.dynamic) ~[the_knocker-1.4.0-forge-1.20.1.jar%23182!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:950) ~[forge-1.20.1-47.3.0-universal.jar%23189!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:835) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:124) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by Shweit** [comment]
same here

**Comment by average-minecrafter** [comment]
same

**Comment by Shweit** [comment]
@average-minecrafter this is fixed in newer versions

**Comment by Closed-Sleet** [comment]
> So I added "the knocker" to my modpack, but at night found this error. Hope it'll be fixed soon..
> 
> ```
> [21:51:51] [Server thread/ERROR]:Encountered an unexpected exceptionjava.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_20185_()" because "knocker" is null
> 	at net.mcreator.theknocker.procedures.SpawnknockerProcedure.execute(SpawnknockerProcedure.java:68) ~[the_knocker-1.4.0-forge-1.20.1.jar%23182!/:?]
> 	at net.mcreator.theknocker.procedures.KnockeventProcedure.execute(KnockeventProcedure.java:66) ~[the_knocker-1.4.0-forge-1.20.1.jar%23182!/:?]
> 	at net.mcreator.theknocker.procedures.KnocksleepProcedure.lambda$execute$1(KnocksleepProcedure.java:65) ~[the_knocker-1.4.0-forge-1.20.1.jar%23182!/:?]
> 	at net.mcreator.theknocker.TheKnockerMod.lambda$tick$2(TheKnockerMod.java:84) ~[the_knocker-1.4.0-forge-1.20.1.jar%23182!/:?]
> 	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
> 	at net.mcreator.theknocker.TheKnockerMod.tick(TheKnockerMod.java:84) ~[the_knocker-1.4.0-forge-1.20.1.jar%23182!/:?]
> 	at net.mcreator.theknocker.__TheKnockerMod_tick_ServerTickEvent.invoke(.dynamic) ~[the_knocker-1.4.0-forge-1.20.1.jar%23182!/:?]
> 	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2387!/:?]
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2387!/:?]
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2387!/:?]
> 	at net.minecraftforge.event.ForgeEventFactory.onPostServerTick(ForgeEventFactory.java:950) ~[forge-1.20.1-47.3.0-universal.jar%23189!/:?]
> 	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:835) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?]
> 	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:124) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?]
> 	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?]
> 	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23184!/:?]
> 	at java.lang.Thread.run(Unknown Source) ~[?:?]
> ```

Having the same issue here after a couple nights
I am using 1.19.2 forge version 43.4.23
My logs are attached
[crash-2025-08-06_08.01.59-server.txt](https://github.com/user-attachments/files/21617689/crash-2025-08-06_08.01.59-server.txt)

**Comment by Shweit** [comment]
@Closed-Sleet which version of the knocker are you using? This Problem is fixed in newer versions of the mod:
https://www.curseforge.com/minecraft/mc-mods/the-knocker/download/5902696

The fixed version is marked as beta on curseforge, that can be the reason you can not find it in the list of version when instaling it via the curseforge app

**Comment by Closed-Sleet** [comment]
> [@Closed-Sleet](https://github.com/Closed-Sleet) which version of the knocker are you using? This Problem is fixed in newer versions of the mod: https://www.curseforge.com/minecraft/mc-mods/the-knocker/download/5902696
> 
> The fixed version is marked as beta on curseforge, that can be the reason you can not find it in the list of version when instaling it via the curseforge app

The beta version appears to have that problem solved. Curseforge doesn't seem to allow modpacks to contain beta versions for the purposes of it being public. As it keeps marking it as a version "not available on curseforge" and not including it in any attempts to share the modpack.
