### ISSUE TITLE
Knocker Spawn Crash

### ISSUE THREAD

**Issue by serioos** [MProductionsmado/The-Knocker#9]
I got another crash while walking around.

[crash-2024-07-01_02.29.19-server.txt](https://github.com/user-attachments/files/16046461/crash-2024-07-01_02.29.19-server.txt)
[latest.log](https://github.com/user-attachments/files/16046463/latest.log)

Minecraft 1.20.1 Forge 47.3.1
the_knocker-1.3.0b-forge-1.20.1.jar

**Comment by Cephelo** [comment]
I am also getting this crash, almost the same stacktraces and everything.  For some reason it didn't generate a crashlog, though.
Here's my bigass latest.log file, it's around line 9206 and continues until 9358: [latest.log](https://gist.githubusercontent.com/Cephelo/5893272dcb9a0f6643c41d25f39301ec/raw/c2d7c21f3c102a729cb710ad907086698ac635a4/2024-07-12-2.log)

Since we both have 300+ mods, here's the list of mods that we BOTH have: 
<details><summary>List of mods:</summary>

## mods
```
AI-Improvements, Ambient Environment, amendments, apotheosis, Apothic Attributes, appleskin, 
architectury, athena, attributefix, attributeslib, balm, Better Combat, biomemusic mod, blueprint, 
Boat Break Fix, bookshelf, Born in Chaos, Bow Infinity Fix, Caelus API, Carry On, chimes, chipped, 
citadel, Cloth Config v10 API, clumps, CoFH Core, collective, configured, controlling, 
cosmetic armor reworked, Critters and Companions, Cupboard utilities, Curios API, DeepslateCutting, 
dungeons_arise, Elytra Slot, Embeddium, Embeddium Extra, Equipment Compare, expandability, 
expanded_sculk_mod, Explorer's Compass, Falling Leaves, Fast Leaf Decay, Fast Paintings, Fast Suite, 
Ferrite Core, flib, FPS Reducer, framework, fusion, GeckoLib, Goblin Traders, 
Golems Are Friends Not Fodder, Guard Villagers, Ice and Fire, iceberg, immediatelyfast, 
Item Collectors, jade, Kiwi Library, Kotlin For Forge, KumaAPI, Let Me Despawn, Light Overlay, 
midnightlib, mixinextras, mixinsquared, modernfix, Moonlight Library, More Villagers, Mouse Tweaks, 
Nature's Compass, No Trample, Not Enough Crashes, notenoughanimations, Overloaded Armor Bar, 
ParCool!, patchouli, Pick Up Notifier, placebo, Player Animator, Presence Footsteps (Forge), 
Puzzles Lib, quark, Resourceful Lib, resourcefulconfig, riverredux, searchables, Simply Swords, 
Snow! Real Magic!, Sound Physics Remastered, Stalwart Dungeons, Structure Gel API, 
SuperMartijn642's Config Lib, SuperMartijn642's Core Lib, supplementaries, terrablender, TheKnocker, 
Vein Mining, villagertools, Visuality: Reforged, wegotrunnners, When Dungeons Arise, YUNG's API, 
YUNG's Better Desert Temples, YUNG's Better Dungeons, YUNG's Better Mineshafts, 
YUNG's Better Nether Fortresses, YUNG's Better Ocean Monuments, YUNG's Better Strongholds, Zeta
```
</details>

I doubt it's most of these, but regardless it should hopefully save some time finding the issue.
This also the same issue as #6, so that one can probably be closed.  It may also be similar or related to #1.

Here's an isolated crash from another log:
<details><summary>Crash Info:</summary>

## crash info
```
[12Jul2024 22:46:51.157] [Render thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.world.entity.Entity.m_20185_()" because "knocker" is null
	Index: 27
	Listeners:
		0: HIGHEST
		1: ASM: class com.kamth.zeldamod.event.ModEvents TickEvents(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		2: HIGH
		3: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		4: NORMAL
		5: ASM: class net.mcreator.combat_expansion.procedures.SpecialAttacksProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		6: ASM: class net.mcreator.combat_expansion.procedures.HoldnothingProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		7: ASM: class net.mcreator.combat_expansion.procedures.HoldTwinbladesProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		8: ASM: class net.mcreator.combat_expansion.procedures.HoldSwordProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		9: ASM: class net.mcreator.combat_expansion.procedures.HoldLongswordProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		10: ASM: class net.mcreator.combat_expansion.procedures.HoldHammerProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		11: ASM: class net.mcreator.combat_expansion.procedures.AttackProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		12: ASM: class com.legacy.structure_gel.core.events.SGClientEvents$ForgeBus clientPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		13: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@7de79690
		14: ASM: class com.forgivingworld.event.EventHandler onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		15: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@23628501
		16: ASM: class net.mcreator.expandedsculkmod.procedures.CorruptedArmorTickEventProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		17: ASM: class dev.shadowsoffire.placebo.patreon.PatreonPreview tick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		18: ASM: com.corosus.zombieawareness.ZAEventHandler@627056cc tickPlayer(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		19: ASM: org.infernalstudios.shieldexp.events.ShieldExpansionEvents@58256714 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		20: ASM: class net.mcreator.spelunkerscharm.procedures.PlayerTickHandlerProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		21: ASM: class tschipp.callablehorses.client.event.KeybindEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		22: ASM: com.corosus.watut.loader.forge.EventHandlerForge@2edb5073 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		23: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@53340b95
		24: ASM: com.mrcrayfish.framework.event.ForgeEvents@778534cd onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		25: ASM: com.github.L_Ender.cataclysm.event.ServerEventHandler@5643b801 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		26: ASM: class net.mcreator.picktorches.procedures.HoldingTorchProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		27: ASM: class net.mcreator.theknocker.procedures.RandomspawnProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		28: ASM: class net.mcreator.theknocker.procedures.PlayertickProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		29: ASM: class net.mcreator.theknocker.procedures.CansleepProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		30: ASM: class exp.fluffynuar.truedarkness.world.inventory.SamovarGUIMenu onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		31: ASM: class exp.fluffynuar.truedarkness.world.inventory.BlacksmiteForgeGUIMenu onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		32: ASM: class exp.fluffynuar.truedarkness.procedures.AnyTicksProcProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		33: ASM: class com.Harbinger.Spore.sEvents.HandlerEvents Effects(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		34: ASM: class invtweaks.events.ServerEvents onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		35: ASM: class net.mcreator.borninchaosv.procedures.WarningSoundProcedure onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		36: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@c9d8313
		37: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@4d8fc706
		38: ASM: INSTANCE onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		39: ASM: class com.github.eterdelta.crittersandcompanions.handler.PlayerHandler onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		40: ASM: com.bobmowzie.mowziesmobs.server.ServerEventHandler@30439edd onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		41: ASM: com.aizistral.enigmaticlegacy.client.QuoteHandler@246469d4 onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		42: ASM: class com.github.sculkhorde.util.ForgeEventSubscriber onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		43: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@7af2093b
		44: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@969cd53
		45: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@690c4276
		46: ASM: com.alrex.parcool.common.action.ActionProcessor@2f9fc29 onTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		47: ASM: com.alrex.parcool.common.action.ActionProcessor@2f9fc29 onTickInClient(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		48: ASM: class net.mehvahdjukaar.supplementaries.common.events.forge.ServerEventsForge onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		49: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@5a880fa6
		50: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@30d96e1d
		51: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@771d2e00
		52: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@7c09cd67
		53: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@66e6087f
		54: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@1d342b38
		55: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@3c76bb0
		56: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@3197ec5a
		57: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@6764afe7
		58: ASM: air onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		59: ASM: air onPlayerTickClient(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		60: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@5bb535d8
		61: ASM: team.creative.playerrevive.server.ReviveEventServer@1433c53d playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		62: ASM: dev.gigaherz.toolbelt.slot.BeltExtensionSlot$EventHandlers@e6c0e4d entityTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		63: ASM: team.creative.playerrevive.client.ReviveEventClient@426ec274 playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		64: net.minecraftforge.eventbus.EventBus$$Lambda$1925/0x00000008009c5ef8@63974ff5
		65: LOWEST
		66: ASM: class com.dragonfight.event.EventHandler onPlayerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
		67: ASM: class cofh.core.common.item.ItemTracker playerTick(Lnet/minecraftforge/event/TickEvent$PlayerTickEvent;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_20185_()" because "knocker" is null
	at TRANSFORMER/the_knocker@1.3.0/net.mcreator.theknocker.procedures.SpawnknockerProcedure.execute(SpawnknockerProcedure.java:63)
	at TRANSFORMER/the_knocker@1.3.0/net.mcreator.theknocker.procedures.RandomeventProcedure.execute(RandomeventProcedure.java:23)
	at TRANSFORMER/the_knocker@1.3.0/net.mcreator.theknocker.procedures.RandomspawnProcedure.execute(RandomspawnProcedure.java:91)
	at TRANSFORMER/the_knocker@1.3.0/net.mcreator.theknocker.procedures.RandomspawnProcedure.onPlayerTick(RandomspawnProcedure.java:32)
	at TRANSFORMER/the_knocker@1.3.0/net.mcreator.theknocker.procedures.__RandomspawnProcedure_onPlayerTick_PlayerTickEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@47.3.0/net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:920)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:285)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.player.AbstractClientPlayer.m_8119_(AbstractClientPlayer.java:70)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.player.LocalPlayer.m_8119_(LocalPlayer.java:189)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:274)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.mixinextras$bridge$accept$181(Level.java)
	at TRANSFORMER/neruina@2.1.0/com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.wrapOperation$ehl000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:8540)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.Level.m_46653_(Level.java:479)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:256)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:254)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1814)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718)
	at TRANSFORMER/minecraft@1.20.1/net.minecraft.client.main.Main.main(Main.java:218)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.0/net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:108)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)

[12Jul2024 22:46:51.160] [Render thread/WARN] [neruina/]: Neruina caught an exception, see below for cause
java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_20185_()" because "knocker" is null
	at net.mcreator.theknocker.procedures.SpawnknockerProcedure.execute(SpawnknockerProcedure.java:63) ~[the_knocker-1.3.0b-forge-1.20.1.jar%23795!/:?]
	at net.mcreator.theknocker.procedures.RandomeventProcedure.execute(RandomeventProcedure.java:23) ~[the_knocker-1.3.0b-forge-1.20.1.jar%23795!/:?]
	at net.mcreator.theknocker.procedures.RandomspawnProcedure.execute(RandomspawnProcedure.java:91) ~[the_knocker-1.3.0b-forge-1.20.1.jar%23795!/:?]
	at net.mcreator.theknocker.procedures.RandomspawnProcedure.onPlayerTick(RandomspawnProcedure.java:32) ~[the_knocker-1.3.0b-forge-1.20.1.jar%23795!/:?]
	at net.mcreator.theknocker.procedures.__RandomspawnProcedure_onPlayerTick_PlayerTickEvent.invoke(.dynamic) ~[the_knocker-1.3.0b-forge-1.20.1.jar%23795!/:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.5.jar%2381!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.5.jar%2381!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.5.jar%2381!/:?]
	at net.minecraftforge.event.ForgeEventFactory.onPlayerPostTick(ForgeEventFactory.java:920) ~[forge-1.20.1-47.3.0-universal.jar%23844!/:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:285) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at net.minecraft.client.player.AbstractClientPlayer.m_8119_(AbstractClientPlayer.java:70) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at net.minecraft.client.player.LocalPlayer.m_8119_(LocalPlayer.java:189) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at net.minecraft.world.level.Level.mixinextras$bridge$accept$181(Level.java) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at com.bawnorton.neruina.handler.TickHandler.safelyTickEntities(TickHandler.java:92) ~[Neruina-2.1.0-forge+1.20.1.jar%23714!/:?]
	at net.minecraft.world.level.Level.wrapOperation$ehl000$neruina$catchTickingEntities$notTheCauseOfTickLag(Level.java:8540) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:256) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:254) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1814) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23839!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.0.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
```
</details>

**Comment by Cephelo** [comment]
Upon looking at serioos's crashlog a bit closer, I came up with a small fix that _should_ prevent this crash from happening.  I've submitted the patch as a pull request: #12
All it does is wrap the if-statement causing the crash (along with another if-statement) in a null check.

**Comment by CodersRage** [comment]
can We get the fix soon I have the same crashing issue and it occurs when ever the knocker spawns
